### ISSUE TITLE
U-Boot Overlays / Cape Manager

### ISSUE THREAD

**Issue by bradstewart** [balena-os/balena-beaglebone#141]
It seems the Kernel Overlays and Cape Manager are now deprecated in favor of U-Boot overlays:
- https://groups.google.com/d/msg/beagleboard/P_Y5yjJyuu4/G0J70kZoAwAJ

Related reading:
 - https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays
 - https://groups.google.com/forum/#!topic/beagleboard/Xv9H7wxDRAE

For what it's worth, I can only load `cape-universal` on ResinOS 2.12.3 by echoing to `/sys/devices/platform/bone_capemgr/slots`. Others (e.g. `cape-universaln`) worked on ResinOS 2.4.2.

It seems to be under active development, and require new/specific versions of U-Boot and the bb-cape-overlays package. This is way outside my area of expertise, so playing around with `uEnv_internal.txt` didn't yield much.

I suspect https://github.com/resin-os/resin-beaglebone/issues/138 is related to this as well.

Is this supported new way of doing things supported on ResinOS?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_bal7)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ghsr)

**Comment by floion** [comment]
Hi @bradstewart can you set-up your cape by using the info here? https://forum.digikey.com/t/all-beaglebone-varients-u-boot-overlays/26
The beaglebones we have on v2.12.3 are running the 2017.01 u-boot version

**Comment by floion** [comment]
Can you try adding "enable_uboot_overlays=1" to uEnv.txt and then
> cat /proc/cmdline

to check if it contains
> bone_capemgr.uboot_capemgr_enabled=1

?

**Comment by bradstewart** [comment]
Will give it a shot today.

**Comment by FRVisser** [comment]
I do have the capamgr working on v2.12.3 with UART 2, 4 and 5.

**Comment by lekkas** [comment]
@bradstewart did you have any progress with enabling uboot?

**Comment by bradstewart** [comment]
I tried once more, was still having trouble with it. Then life happened, we deployed a workaround instead, and I haven't had time to circle back on it yet.

**Comment by floion** [comment]
Implemented by https://github.com/balena-os/balena-beaglebone/pull/171
These changes will be in OS version v2.29.2+rev1 or newer

**Comment by jadonk** [comment]
> 
> 
> Can you try adding "enable_uboot_overlays=1" to uEnv.txt and then
> 
> > cat /proc/cmdline
> 
> to check if it contains
> 
> > bone_capemgr.uboot_capemgr_enabled=1
> 
> ?

Where do you edit uEnv.txt in a running image? I tried /mnt/boot/uEnv.txt, but the setting didn't show up.
