### ISSUE TITLE
Kernel audit seems to be enabled?

### ISSUE THREAD

**Issue by pcarranzav** [balena-os/balena-beaglebone#144]
Looking at journal logs for a 2.7.5 device, there were a lot of "AUDIT" messages in the logs. It would be good to check if latest versions also have this enabled, and disable it since it only floods the logs.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c6gj)

**Comment by ZubairLK** [comment]
yea it is.
```
root@5a524b5:~# cat /proc/config.gz | gunzip | grep -i audit
CONFIG_AUDIT=y
CONFIG_HAVE_ARCH_AUDITSYSCALL=y
CONFIG_AUDITSYSCALL=y
CONFIG_AUDIT_WATCH=y
CONFIG_AUDIT_TREE=y
CONFIG_NETFILTER_XT_TARGET_AUDIT=m
CONFIG_SECURITY_TOMOYO_MAX_AUDIT_LOG=1024
CONFIG_INTEGRITY_AUDIT=y
CONFIG_AUDIT_GENERIC=y
# CONFIG_AUDIT_ARCH_COMPAT_GENERIC is not set
root@5a524b5:~# 
```

I think it is coming from 

```
zubairlk@zubair-xps-resin:~/resin/yocto/resin-beaglebone/layers$ search audit meta-resin-beaglebone/
meta-resin-beaglebone/recipes-kernel/linux/linux-beagleboard-4.14/defconfig:224:CONFIG_NETFILTER_XT_TARGET_AUDIT=m
zubairlk@zubair-xps-resin:~/resin/yocto/resin-beaglebone/layers$ 
```

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-beaglebone/pull/183
