### ISSUE TITLE
Add wl12xx firmware if needed

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-beaglebone#155]
https://github.com/resin-os/meta-resin/pull/1223 removes wl12xx firmware.

It is TI wireless firmware. It might be that it is needed by the beagle line of boards.

**Comment by ZubairLK** [comment]
An easy way to check would be if `CONFIG_WL12XX` `CONFIG_WL1251` are compiled in the kernel or not

```
cat /proc/config.gz | gunzip -d | grep -i wlan_vendor_ti -C5
```

**Comment by floion** [comment]
Closing this now as we are using v.29.2 meta-balena and that change did not impact us
