### ISSUE TITLE
Regression: Missing dtb overlay in 2.15.1

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-beaglebone#156]
am335x-boneblack-emmc-overlay.dtb is missing on 2.15.1, while it was present in 2.12.x (checked 2.12.3, 2.12.7).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ewoz)

**Comment by spanceac** [comment]
Fixed by https://github.com/balena-os/balena-beaglebone/pull/171
