### ISSUE TITLE
Cannot boot v2.26.0+rev1

### ISSUE THREAD

**Issue by FRVisser** [balena-os/balena-beaglebone#159]
Hi, 

I just tried newly released v2.26.0+rev1 on staging. However the beaglebone isn't able to boot. Uboot keeps printing: 
```
U-Boot SPL 2018.01-geac41e26ac (Nov 23 2018 - 09:38:17)
Trying to boot from MMC1
```
I did use a `dev` image, all other complete standard.

Thanks.

**Comment by FRVisser** [comment]
Just tried an production image and a couple of different SD-cards, same issue.

**Comment by floion** [comment]
@FRVisser this should be fixed now.
We were aware of the issues, staging images never reach production without going through our testing suite.
Feel free to close this once you get a chance to test it

**Comment by floion** [comment]
@FRVisser can this be closed now?

**Comment by FRVisser** [comment]
Yes, thanks!
