### ISSUE TITLE
PocketBeagle ethernet over microUSB doesn't get IP on v2.29.0+rev1

### ISSUE THREAD

**Issue by spanceac** [balena-os/balena-beaglebone#170]
Before version v2.29.0+rev1 in order to obtain internet connectivity from a Linux host via onboard microUSB on PocketBeagle you would do the following:
Open nm-connection-editor on the host and edit the connection created by PocketBeagle when plugged. In the "IPv4 Settings" tab > Method > select "Shared to other computers". Then disconnect the board and plug it back in and the board will get an IP address.

Now on v2.29.0+rev1 the PocketBeagle doesn't automatically get an IP over the interface. Manually doing `udhcpc` will get an IP for the board.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-beaglebone/pull/172
