### ISSUE TITLE
User wants support for networking over USB

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-beaglebone#188]
User would like USB networking just like how BeagleBone Black's Angstrom Distribution allows you to plug the device on your computer with a USB and SSH to the device on 192.168.7.2 .
See: https://elinux.org/Beagleboard:Terminal_Shells#SSH:_BeagleBone.27s_IP_Address
See: https://learn.adafruit.com/ssh-to-beaglebone-black-over-usb/overview

**Comment by zvin** [comment]
Assign a static ip to this interface by creating a NetworkManager config file in the `system-connections` folder of the boot partition, see https://www.balena.io/docs/reference/OS/network/2.x/#setting-a-static-ip .
Configure the computer on the other side of the usb cable to use a static ip address in the same network on the usb network interface.

Slightly more complicated solution: run a DHCP server on the beaglebone so any computer on the other side of the usb cable gets an ip address automatically (this is what the official beaglebone disk images do).
