### ISSUE TITLE
Bump kernel to 5.4.70-ti-r21 for hm3301 module support

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-beaglebone#253]
The driver in question is hm3301 and we want to enable CONFIG_HM3301 for the beaglebone black.

**Comment by jadonk** [comment]
Is there a way I can help?

**Comment by acostach** [comment]
Thank you @jadonk , the kernel update and the module was actually intended for the Beaglebone Green Gateway, and now the image 2.67.3+rev1 is available for it in production. If you need this kernel and module combo for the Beaglebone Black, please re-open this ticket and let us know.
