### ISSUE TITLE
5.4 kernel is randomly not able to detect the PHY on a BBB industrial

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-beaglebone#272]
The exact device where this was reported is:

https://www.cnx-software.com/2016/01/28/beaglebone-black-industrial-4g-is-red-and-offers-an-extended-temperature-range/

On 4.14 (previous OS):
```
May 20 07:32:39 localhost kernel: davinci_mdio 4a101000.mdio: davinci mdio revision 1.6, bus freq 1000000
May 20 07:32:39 localhost kernel: davinci_mdio 4a101000.mdio: detected phy mask fffffffb
May 20 07:32:39 localhost kernel: MDIO: davinci_mdio: dt: updated phy_id[2] from phy_mask[fffffffb]
May 20 07:32:39 localhost kernel: libphy: 4a101000.mdio: probed
May 20 07:32:39 localhost kernel: davinci_mdio 4a101000.mdio: phy[2]: device 4a101000.mdio:02, driver SMSC LAN8710/LAN8720
```
On 5.4 (new OS):
```
May 20 07:47:29 localhost kernel: libphy: Fixed MDIO Bus: probed
May 20 07:47:29 localhost kernel: davinci_mdio 4a101000.mdio: davinci mdio revision 1.6, bus freq 1000000
May 20 07:47:29 localhost kernel: mdio_bus 4a101000.mdio: MDIO device at address 0 is missing
```

We are still gathering details to help pinpoint the versions, but this would probably need a reboot loop test with ethernet check.

**Comment by floion** [comment]
Tried to catch the problem on our hardware we have here and we could not reproduce the problem in over a few thousands reboots. So if the customer is able to ship us one of the boards that exhibit the problem then we can better implement the workaround.
