### ISSUE TITLE
Request: Release for BeagleBone Black including balenaEngine 20.10.16

### ISSUE THREAD

**Issue by lmbarros** [balena-os/balena-beaglebone#309]
For context, we currently have a [PR open](https://github.com/balena-os/meta-balena/pull/2583) (but not merged yet) to upgrade meta-balena for this balenaEngine version.

**Comment by lmbarros** [comment]
But see also this one: https://github.com/balena-os/balena-beaglebone/issues/337 (which requests a v2.98.4 or later release, and thus "obsoletes" this request here).

(I'll not close the issue to avoid a bogus snapback. I think it's better to close this and #337 at the same time.)

**Comment by floion** [comment]
Done, newer OS releases are available which contain newer balenaEngine versions
