### ISSUE TITLE
tests: hup: Running out of space during final hup test

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-os/balena-beaglebone#336]
https://jenkins.product-os.io/job/leviathan-v2-template/759/artifact/reports/worker-74103ce-hup-beaglebone-black.log

**Comment by klutchell** [comment]
balenaHUP will [delete all docker files](https://github.com/balena-os/balenahup/pull/371) on the inactive partition before proceeding with hostapp-update, and we should probably do the same in our hup tests to resolve this.
